import type { Theme } from './types';

export const modernThemes: Theme[] = [
  {
    id: 'notion',
    name: 'Notion',
    description: '极致克制的黑白灰，纯粹信息密度',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.6 !important; color: #37352f !important; background-color: #ffffff !important; word-wrap: break-word;',
      h1: 'font-size: 34px; font-weight: 700; color: #37352f !important; line-height: 1.2 !important; margin: 38px 0 8px; letter-spacing: -0.02em;',
      h2: 'font-size: 26px; font-weight: 600; color: #37352f !important; line-height: 1.3 !important; margin: 32px 0 8px;',
      h3: 'font-size: 21px; font-weight: 600; color: #37352f !important; line-height: 1.35 !important; margin: 28px 0 8px;',
      h4: 'font-size: 18px; font-weight: 600; color: #37352f !important; line-height: 1.4 !important; margin: 24px 0 8px;',
      p: 'margin: 4px 0 !important; line-height: 1.6 !important; color: #37352f !important;',
      strong: 'font-weight: 700; color: #37352f !important;',
      em: 'font-style: italic; color: #37352f !important;',
      a: 'color: #37352f !important; text-decoration: underline; text-underline-offset: 3px; text-decoration-color: rgba(55,53,47,0.4);',
      ul: 'margin: 4px 0; padding-left: 26px;',
      ol: 'margin: 4px 0; padding-left: 26px;',
      li: 'margin: 2px 0; line-height: 1.6 !important; color: #37352f !important;',
      blockquote: 'margin: 8px 0; padding: 4px 16px; background-color: transparent !important; border-left: 3px solid #37352f; color: #37352f !important; border-radius: 0;',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 2px 5px; background-color: #f7f6f3 !important; color: #eb5757 !important; border-radius: 3px; font-size: 13px !important; line-height: 1.5 !important;',
      pre: 'margin: 16px 0; padding: 20px; background-color: #f7f6f3 !important; border-radius: 4px; overflow-x: auto; font-size: 13px !important; line-height: 1.5 !important;',
      hr: 'margin: 24px auto; border: none; height: 1px; background-color: #e9e9e7 !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 16px auto; border-radius: 2px;',
      table: 'width: 100%; margin: 16px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #f7f6f3 !important; padding: 8px 12px; text-align: left; font-weight: 600; color: #37352f !important; border: 1px solid #e9e9e7;',
      td: 'padding: 8px 12px; border: 1px solid #e9e9e7; color: #37352f !important;',
      tr: 'border: none;',
    }
  },
  {
    id: 'github',
    name: 'GitHub',
    description: '开发者最熟悉的阅读界面，README 即视感',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif; font-size: 16px; line-height: 1.6 !important; color: #1f2328 !important; background-color: #ffffff !important; word-wrap: break-word;',
      h1: 'font-size: 32px; font-weight: 600; color: #1f2328 !important; line-height: 1.25 !important; margin: 24px 0 16px; padding-bottom: 10px; border-bottom: 1px solid #d1d9e0;',
      h2: 'font-size: 24px; font-weight: 600; color: #1f2328 !important; line-height: 1.25 !important; margin: 24px 0 16px; padding-bottom: 8px; border-bottom: 1px solid #d1d9e0;',
      h3: 'font-size: 20px; font-weight: 600; color: #1f2328 !important; line-height: 1.25 !important; margin: 24px 0 16px;',
      h4: 'font-size: 16px; font-weight: 600; color: #1f2328 !important; line-height: 1.25 !important; margin: 24px 0 16px;',
      p: 'margin: 16px 0 !important; line-height: 1.6 !important; color: #1f2328 !important;',
      strong: 'font-weight: 600; color: #1f2328 !important;',
      em: 'font-style: italic; color: #1f2328 !important;',
      a: 'color: #0969da !important; text-decoration: underline; text-underline-offset: 2px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 4px 0; line-height: 1.6 !important; color: #1f2328 !important;',
      blockquote: 'margin: 16px 0; padding: 8px 16px; background-color: transparent !important; border-left: 4px solid #d0d7de; color: #656d76 !important; border-radius: 0;',
      code: 'font-family: "SF Mono", Consolas, "Liberation Mono", Menlo, monospace; padding: 3px 6px; background-color: rgba(175,184,193,0.2) !important; color: #1f2328 !important; border-radius: 6px; font-size: 13px !important; line-height: 1.5 !important;',
      pre: 'margin: 16px 0; padding: 16px; background-color: #f6f8fa !important; border-radius: 6px; overflow-x: auto; font-size: 13px !important; line-height: 1.45 !important;',
      hr: 'margin: 24px auto; border: none; height: 3px; background-color: #d1d9e0 !important; width: 100%; border-radius: 2px;',
      img: 'max-width: 100%; height: auto; display: block; margin: 16px auto; border-radius: 6px;',
      table: 'width: 100%; margin: 16px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #f6f8fa !important; padding: 8px 16px; text-align: left; font-weight: 600; color: #1f2328 !important; border: 1px solid #d1d9e0;',
      td: 'padding: 8px 16px; border: 1px solid #d1d9e0; color: #1f2328 !important;',
      tr: 'border: none;',
    }
  },
  {
    id: 'dracula',
    name: 'Dracula',
    description: '暗紫色赛博吸血鬼美学，粉青撞色',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #f8f8f2 !important; background-color: #282a36 !important; word-wrap: break-word;',
      h1: 'font-size: 32px; font-weight: 700; color: #bd93f9 !important; line-height: 1.3 !important; margin: 38px 0 16px;',
      h2: 'font-size: 26px; font-weight: 600; color: #ff79c6 !important; line-height: 1.35 !important; margin: 32px 0 16px;',
      h3: 'font-size: 21px; font-weight: 600; color: #8be9fd !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #50fa7b !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 18px 0 !important; line-height: 1.7 !important; color: #f8f8f2 !important;',
      strong: 'font-weight: 700; color: #ffb86c !important;',
      em: 'font-style: italic; color: #8be9fd !important;',
      a: 'color: #8be9fd !important; text-decoration: none; border-bottom: 1px solid #8be9fd; padding-bottom: 1px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.7 !important; color: #f8f8f2 !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: #44475a !important; border-left: 4px solid #bd93f9; color: #f8f8f2 !important; border-radius: 4px;',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #44475a !important; color: #50fa7b !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #44475a !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;',
      hr: 'margin: 36px auto; border: none; height: 1px; background-color: #6272a4 !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #44475a !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #bd93f9 !important; border: 1px solid #6272a4;',
      td: 'padding: 12px 16px; border: 1px solid #6272a4; color: #f8f8f2 !important;',
      tr: 'border: none;',
    }
  },
  {
    id: 'sakura',
    name: '樱花',
    description: '柔粉色日式美学，温柔感性的少女心表达',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.75 !important; color: #4a3f4f !important; background-color: #fef7f9 !important; word-wrap: break-word;',
      h1: 'font-size: 32px; font-weight: 700; color: #c44569 !important; line-height: 1.3 !important; margin: 38px 0 16px;',
      h2: 'font-size: 26px; font-weight: 600; color: #c44569 !important; line-height: 1.35 !important; margin: 32px 0 16px;',
      h3: 'font-size: 21px; font-weight: 600; color: #4a3f4f !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #4a3f4f !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 18px 0 !important; line-height: 1.75 !important; color: #4a3f4f !important;',
      strong: 'font-weight: 700; color: #c44569 !important; background-color: rgba(196,69,105,0.06); padding: 0 4px; border-radius: 4px;',
      em: 'font-style: italic; color: #9b7fa7 !important;',
      a: 'color: #c44569 !important; text-decoration: none; border-bottom: 1px solid rgba(196,69,105,0.3); padding-bottom: 1px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.75 !important; color: #4a3f4f !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: #fceef2 !important; border-left: 4px solid #e8a0b4; color: #6b5570 !important; border-radius: 8px;',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #fceef2 !important; color: #c44569 !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #fceef2 !important; border-radius: 12px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;',
      hr: 'margin: 36px auto; border: none; height: 1px; background-color: #f0d4dd !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 12px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #fceef2 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #4a3f4f !important; border: 1px solid #f0d4dd;',
      td: 'padding: 12px 16px; border: 1px solid #f0d4dd; color: #4a3f4f !important;',
      tr: 'border: none;',
    }
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    description: '霓虹赛博朋克世界，品红与青的极致碰撞',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: "SF Mono", "Fira Code", Consolas, monospace; font-size: 15px; line-height: 1.7 !important; color: #e0e0ff !important; background-color: #0d0221 !important; word-wrap: break-word;',
      h1: 'font-size: 32px; font-weight: 700; color: #ff2a6d !important; text-shadow: 0 0 8px rgba(255,42,109,0.5); line-height: 1.3 !important; margin: 38px 0 16px; text-transform: uppercase;',
      h2: 'font-size: 26px; font-weight: 600; color: #05d9e8 !important; text-shadow: 0 0 8px rgba(5,217,232,0.5); line-height: 1.35 !important; margin: 32px 0 16px;',
      h3: 'font-size: 21px; font-weight: 600; color: #d1f7ff !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #ff2a6d !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 18px 0 !important; line-height: 1.7 !important; color: #e0e0ff !important;',
      strong: 'font-weight: 700; color: #ff2a6d !important; text-shadow: 0 0 6px rgba(255,42,109,0.4);',
      em: 'font-style: italic; color: #05d9e8 !important;',
      a: 'color: #05d9e8 !important; text-decoration: none; border-bottom: 1px solid #05d9e8; padding-bottom: 1px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.7 !important; color: #e0e0ff !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: #1a0a3e !important; border-left: 4px solid #ff2a6d; color: #c8c8ff !important; border-radius: 0;',
      code: 'font-family: "SF Mono", "Fira Code", Consolas, monospace; padding: 3px 6px; background-color: #1a0a3e !important; color: #05d9e8 !important; border-radius: 0; font-size: 13px !important; line-height: 1.5 !important; border: 1px solid #2a1a4e;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #1a0a3e !important; border-radius: 0; overflow-x: auto; font-size: 13px !important; line-height: 1.5 !important; border: 1px solid #2a1a4e;',
      hr: 'margin: 36px auto; border: none; height: 2px; background: linear-gradient(90deg, #ff2a6d, #05d9e8) !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 0;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 14px;',
      th: 'background-color: #1a0a3e !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #ff2a6d !important; border: 1px solid #2a1a4e;',
      td: 'padding: 12px 16px; border: 1px solid #2a1a4e; color: #e0e0ff !important;',
      tr: 'border: none;',
    }
  },
];
